export const mockTripInfoItems = [
  {
    placeId: 'test',
    placeName: '백련사',
    placeType: '관광 명소',
    placeDesc: '천년 고찰의 고즈넉함과 동백나무 숲길이 어우러진 강진의 명소',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-05'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '다산초당',
    placeType: '역사 명소',
    placeDesc: '다산 정약용 선생이 유배 시절에 학문을 닦았던 역사적 장소',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-05'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '강진만 한정식',
    placeType: '음식점',
    placeDesc: '강진의 산해진미를 한상 가득 즐길 수 있는 프리미엄 한정식',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-05'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '가우도 출렁다리',
    placeType: '관광 명소',
    placeDesc: '바다 위를 걷는 짜릿한 경험과 함께 보는 가우도의 절경',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-05'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '강진펜션',
    placeType: '숙소',
    placeDesc: 'Text Text Text Text Text Text Text Text Text Text ',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-05'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '백련사',
    placeType: '관광 명소',
    placeDesc: '천년 고찰의 고즈넉함과 동백나무 숲길이 어우러진 강진의 명소',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-06'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '다산초당',
    placeType: '역사 명소',
    placeDesc: '다산 정약용 선생이 유배 시절에 학문을 닦았던 역사적 장소',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-06'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '강진만 한정식',
    placeType: '음식점',
    placeDesc: '강진의 산해진미를 한상 가득 즐길 수 있는 프리미엄 한정식',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-06'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '가우도 출렁다리',
    placeType: '관광 명소',
    placeDesc: '바다 위를 걷는 짜릿한 경험과 함께 보는 가우도의 절경',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-06'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '강진펜션',
    placeType: '숙소',
    placeDesc: 'Text Text Text Text Text Text Text Text Text Text ',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-06'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '백련사',
    placeType: '관광 명소',
    placeDesc: '천년 고찰의 고즈넉함과 동백나무 숲길이 어우러진 강진의 명소',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-07'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '다산초당',
    placeType: '역사 명소',
    placeDesc: '다산 정약용 선생이 유배 시절에 학문을 닦았던 역사적 장소',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-07'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '강진만 한정식',
    placeType: '음식점',
    placeDesc: '강진의 산해진미를 한상 가득 즐길 수 있는 프리미엄 한정식',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-07'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '가우도 출렁다리',
    placeType: '관광 명소',
    placeDesc: '바다 위를 걷는 짜릿한 경험과 함께 보는 가우도의 절경',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-07'),
    distKm: 3200,
  },
  {
    placeId: 'test',
    placeName: '강진펜션',
    placeType: '숙소',
    placeDesc: 'Text Text Text Text Text Text Text Text Text Text ',
    placeMap: 'https://place.map.kakao.com/25041679',
    date: new Date('2026-09-07'),
    distKm: 3200,
  },
];
